#!/bin/sh

clear

echo """
---------------
"""

./_gunicorn_manager status

echo """
---------------
"""

./_redis_manager status

echo """
---------------
"""

./_worker_manager status

echo """
---------------
"""
